### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by yeahimfreaky**

### CODE REVIEW

**Comment by CVarisco** [comment]
Hi @yeahimfreaky 
Thanks a lot for your contribution.
You are so funny 😂

But the story shouldn't be vulgar, I'm closing this merge request.

Thanks again for your time 🙂

**Comment by yeahimfreaky** [comment]
How is being gay vulgar, or funny?

**Comment by GabbySeligman** [comment]
Honestly, what's wrong with being gay, @CVarisco?

**Comment by CVarisco** [comment]
Nothing :)

I found the merge request not serious, only this.
I'm sorry for that.
I'm very happy to accept merge request that continue the story in a positive way 😃

Have a nice day 🤠

**Pull request closed without merging**
